### ISSUE TITLE
Question: is there a way to `pip install` starfish

### ISSUE THREAD

**Issue by shark8me** [DEX-Company/starfish-py#106]
Is there a way to `pip install starfish` , so that it can be used in a different project (e.g. Invoke?)

Squid-py's docs seem to suggest this could work (off a Github branch)
`pip install git+https://github.com/oceanprotocol/squid-py.git@develop`

Would a similar thing work for starfish-py?

**Comment by shark8me** [comment]
Just wanted to add that when I try this: `pip install git+https://github.com/DEX-Company/starfish-py@develop`, `import starfish` does work.
However some squid_py imports fail: 
`Using default logging settings.
Traceback (most recent call last):
  File "purch_asset.py", line 21, in <module>
    from squid_py import ACCESS_SERVICE_TEMPLATE_ID
ImportError: cannot import name 'ACCESS_SERVICE_TEMPLATE_ID'
`,
despite importing squid_py in the same fashion

**Comment by shark8me** [comment]
@billbsing post updating with the new branch, I get a different error:

To import, I do 

```bash
virtualenv -p /usr/bin/python3.6 venv
source venv/bin/activate
pip install git+https://github.com/DEX-Company/starfish-py@develop
python3 test_squid_agent.py 

```

which returns this error 
```bash
(venv) kiran@kiran-ThinkPad-L460:~/src/github/swagger-codegen/out/flask-invoke$ python3 test_squid_agent.py 
Using default logging settings.
2019-02-22 19:20:27 kiran-ThinkPad-L460 config[762] DEBUG Config: loading from dict {'keeper-contracts': {'keeper.url': 'http://localhost:8545', 'keeper.path': 'artifacts', 'secret_store.url': 'http://localhost:12001', 'parity.url': 'http://localhost:8545'}, 'resources': {'aquarius.url': 'http://localhost:5000', 'brizo.url': 'http://localhost:8030', 'storage.path': 'squid_py.db'}}
2019-02-22 19:20:27 kiran-ThinkPad-L460 keeper[762] DEBUG Loaded Dispenser at 0x69b92271dE6Bb09F11e9927EbD04db0afb284467
2019-02-22 19:20:27 kiran-ThinkPad-L460 keeper[762] DEBUG Loaded OceanToken at 0x0Be67eC5a5908Ba495A5be4d320573EE98c44068
2019-02-22 19:20:27 kiran-ThinkPad-L460 keeper[762] DEBUG Loaded DIDRegistry at 0x75036ff443d6493Bf5108df25700000B0E9975Ec
2019-02-22 19:20:27 kiran-ThinkPad-L460 keeper[762] DEBUG Loaded ServiceExecutionAgreement at 0xEF975E9a229ff4c87C1d5f55d55119A7954056d8
2019-02-22 19:20:27 kiran-ThinkPad-L460 keeper[762] DEBUG Loaded PaymentConditions at 0x81AEc6002ca81cec74AC78ab142Fe3526f879455
2019-02-22 19:20:27 kiran-ThinkPad-L460 keeper[762] DEBUG Loaded AccessConditions at 0x47ADe42c35134AC399b276Ff13D01EF3Db0f71D5
2019-02-22 19:20:27 kiran-ThinkPad-L460 squid_py.keeper.diagnostics[762] INFO Keeper contract artifacts (JSON abi files) at: /home/kiran/src/github/swagger-codegen/out/flask-invoke/venv/artifacts
2019-02-22 19:20:27 kiran-ThinkPad-L460 squid_py.keeper.diagnostics[762] INFO Using keeper contracts from network spree, network id is 8996
2019-02-22 19:20:27 kiran-ThinkPad-L460 squid_py.keeper.diagnostics[762] INFO Looking for keeper contracts ending with ".spree.json", e.g. "ServiceExecutionAgreement.spree.json".
2019-02-22 19:20:27 kiran-ThinkPad-L460 root[762] INFO Finished loading keeper contracts:
	Dispenser: 0x69b92271dE6Bb09F11e9927EbD04db0afb284467
	OceanToken: 0x0Be67eC5a5908Ba495A5be4d320573EE98c44068
	DIDRegistry: 0x75036ff443d6493Bf5108df25700000B0E9975Ec
	ServiceExecutionAgreement: 0xEF975E9a229ff4c87C1d5f55d55119A7954056d8
	PaymentConditions: 0x81AEc6002ca81cec74AC78ab142Fe3526f879455
	AccessConditions: 0x47ADe42c35134AC399b276Ff13D01EF3Db0f71D5
Traceback (most recent call last):
  File "/home/kiran/src/github/swagger-codegen/out/flask-invoke/venv/lib/python3.6/site-packages/web3/contract.py", line 1363, in call_contract_function
    output_data = decode_abi(output_types, return_data)
  File "/home/kiran/src/github/swagger-codegen/out/flask-invoke/venv/lib/python3.6/site-packages/eth_abi/abi.py", line 96, in decode_abi
    return decoder(stream)
  File "/home/kiran/src/github/swagger-codegen/out/flask-invoke/venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 118, in __call__
    return self.decode(stream)
  File "/home/kiran/src/github/swagger-codegen/out/flask-invoke/venv/lib/python3.6/site-packages/eth_utils/functional.py", line 46, in inner
    return callback(fn(*args, **kwargs))
  File "/home/kiran/src/github/swagger-codegen/out/flask-invoke/venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 164, in decode
    yield decoder(stream)
  File "/home/kiran/src/github/swagger-codegen/out/flask-invoke/venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 118, in __call__
    return self.decode(stream)
  File "/home/kiran/src/github/swagger-codegen/out/flask-invoke/venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 186, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/home/kiran/src/github/swagger-codegen/out/flask-invoke/venv/lib/python3.6/site-packages/eth_abi/decoding.py", line 296, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_squid_agent.py", line 159, in <module>
    test_asset()
  File "test_squid_agent.py", line 80, in test_asset
    assert ocean.accounts
  File "/home/kiran/src/github/swagger-codegen/out/flask-invoke/venv/lib/python3.6/site-packages/starfish/ocean/ocean.py", line 163, in accounts
    model = SquidModel(self)
  File "/home/kiran/src/github/swagger-codegen/out/flask-invoke/venv/lib/python3.6/site-packages/starfish/models/squid_model.py", line 33, in __init__
    self._squid_ocean = self.get_squid_ocean()
  File "/home/kiran/src/github/swagger-codegen/out/flask-invoke/venv/lib/python3.6/site-packages/starfish/models/squid_model.py", line 233, in get_squid_ocean
    return SquidOcean(config)
  File "/home/kiran/src/github/swagger-codegen/out/flask-invoke/venv/lib/python3.6/site-packages/squid_py/ocean/ocean.py", line 92, in __init__
    Diagnostics.check_deployed_agreement_templates()
  File "/home/kiran/src/github/swagger-codegen/out/flask-invoke/venv/lib/python3.6/site-packages/squid_py/keeper/diagnostics.py", line 18, in check_deployed_agreement_templates
    template_owner = keeper.service_agreement.get_template_owner(ACCESS_SERVICE_TEMPLATE_ID)
  File "/home/kiran/src/github/swagger-codegen/out/flask-invoke/venv/lib/python3.6/site-packages/squid_py/keeper/service_execution_agreement.py", line 130, in get_template_owner
    return self.contract_concise.getTemplateOwner(template_id)
  File "/home/kiran/src/github/swagger-codegen/out/flask-invoke/venv/lib/python3.6/site-packages/web3/contract.py", line 879, in __call__
    return self.__prepared_function(*args, **kwargs)
  File "/home/kiran/src/github/swagger-codegen/out/flask-invoke/venv/lib/python3.6/site-packages/web3/contract.py", line 892, in __prepared_function
    return getattr(self._function(*args), modifier)(modifier_dict)
  File "/home/kiran/src/github/swagger-codegen/out/flask-invoke/venv/lib/python3.6/site-packages/web3/contract.py", line 1106, in call
    **self.kwargs
  File "/home/kiran/src/github/swagger-codegen/out/flask-invoke/venv/lib/python3.6/site-packages/web3/contract.py", line 1385, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not transact with/call contract function, is contract deployed correctly and chain synced?

```
